### ISSUE TITLE
gnome-chess snap is uninstallable if .deb is already installed

### ISSUE THREAD

**Issue by jbicha** [ubuntu/gnome-chess#4]
- Ubuntu 23.04
- gnome-chess 1:43.2-1 .deb

Test Case
-------------
sudo apt install gnome-chess

snap install gnome-chess

What Happens
-------------------
```
$ snap install gnome-chess
error: cannot perform the following tasks:
- Run configure hook of "gnome-chess" snap if present (run hook "configure": 
-----
cannot update snap namespace: cannot create symlink in "/etc/gnome-chess":
 existing file in the way
snap-update-ns failed with code 1
-----)
```

Other Info
-------------
Ubuntu Cinnamon 23.04 installs the gnome-chess .deb by default

**Comment by kenvandine** [comment]
I've released the broken version to a branch in the store to reference in a bug report to snapd.  Revision 83 reproduces the issue and is published to "stable/broken-layout" for easier testing.

**Comment by kenvandine** [comment]
snapd bug reported at https://bugs.launchpad.net/snapd/+bug/2016342

**Comment by jbicha** [comment]
@kenvandine Could you push gnome-chess rev 85 to stable?

**Comment by kenvandine** [comment]
> 

Done
